USE [C:\USERS\HYAGO ALVES\SOURCE\REPOS\TESTE-PRATICO-FS\FI.WEBATIVIDADEENTREVISTA\APP_DATA\BANCODEDADOS.MDF]
GO

/****** Object:  StoredProcedure [dbo].[FI_SP_ConsBeneficiarios]    Script Date: 28/10/2024 20:26:35 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



CREATE PROC [dbo].[FI_SP_ConsBeneficiarios]
	@IDCLIENTE BIGINT
AS
BEGIN
	SELECT 
		ID,
		NOME, 
		CPF, 
		IDCLIENTE
	FROM BENEFICIARIOS WITH(NOLOCK) 
	WHERE IDCLIENTE = @IDCLIENTE
END
GO


