USE [C:\USERS\HYAGO ALVES\SOURCE\REPOS\TESTE-PRATICO-FS\FI.WEBATIVIDADEENTREVISTA\APP_DATA\BANCODEDADOS.MDF]
GO

/****** Object:  StoredProcedure [dbo].[FI_SP_IncBeneficiario]    Script Date: 28/10/2024 20:28:00 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



CREATE PROC [dbo].[FI_SP_IncBeneficiario]
    @NOME			VARCHAR (50) ,
	@CPF			VARCHAR (11),
    @IDCLIENTE		BIGINT
AS
BEGIN
	INSERT INTO BENEFICIARIOS(NOME, CPF, IDCLIENTE) 
	VALUES (@NOME, @CPF, @IDCLIENTE)

	SELECT SCOPE_IDENTITY()
END
GO


