USE [C:\USERS\HYAGO ALVES\SOURCE\REPOS\TESTE-PRATICO-FS\FI.WEBATIVIDADEENTREVISTA\APP_DATA\BANCODEDADOS.MDF]
GO

/****** Object:  StoredProcedure [dbo].[FI_SP_VerificaCliente]    Script Date: 28/10/2024 20:30:35 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROC [dbo].[FI_SP_VerificaCliente]
	@CPF VARCHAR(14)
AS
BEGIN
	SELECT 1 FROM CLIENTES WHERE CPF = @CPF
END
GO


