USE [C:\USERS\HYAGO ALVES\SOURCE\REPOS\TESTE-PRATICO-FS\FI.WEBATIVIDADEENTREVISTA\APP_DATA\BANCODEDADOS.MDF]
GO

/****** Object:  StoredProcedure [dbo].[FI_SP_DelBenef]    Script Date: 28/10/2024 20:27:36 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



CREATE PROCEDURE [dbo].[FI_SP_DelBenef]
    @Id BIGINT
AS
BEGIN
    DELETE FROM BENEFICIARIOS
    WHERE ID = @Id;
END
GO


