USE [C:\USERS\HYAGO ALVES\SOURCE\REPOS\TESTE-PRATICO-FS\FI.WEBATIVIDADEENTREVISTA\APP_DATA\BANCODEDADOS.MDF]
GO

/****** Object:  StoredProcedure [dbo].[FI_SP_IncCliente]    Script Date: 28/10/2024 20:28:32 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROC [dbo].[FI_SP_IncCliente]
	@CPF           VARCHAR (11),
    @NOME          VARCHAR (50) ,
    @SOBRENOME     VARCHAR (255),
    @NACIONALIDADE VARCHAR (50) ,
    @CEP           VARCHAR (9)  ,
    @ESTADO        VARCHAR (2)  ,
    @CIDADE        VARCHAR (50) ,
    @LOGRADOURO    VARCHAR (500),
    @EMAIL         VARCHAR (2079)
AS
BEGIN
	INSERT INTO CLIENTES (CPF) VALUES (@CPF)
END
GO


